app = "kayako-help-bot"  # Updated app name

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[experimental]
  allowed_public_ports = []
  auto_rollback = true 