# fly.toml app configuration file generated for kayako-call-bot on 2025-02-20T08:40:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kayako-call-bot'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
